title: Limehouse Labs
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Limehouse Labs is a small collaborative workshop based at Limehouse Town Hall in London.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.limehouselabs.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: limehouselabs
github_username:  limehouselabs

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
